server:
  port: 8080
spring:
  application:
    name: gateway-ms
  cloud:
    gateway:
      discovery:
        locator:
          enabled: 'true'
      routes:
      - id: grades-ms
        uri: lb://GRADES-MS
        predicates:
          - Path=/grades/**

      - id: student-ms
        uri: lb://STUDENT-MS
        predicates:
          - Path=/student/**
    loadbalancer:
      enabled: true


eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}